name: petdo_k
description: Mobile App phi lợi nhuận để cứu trợ chó mèo hoang dã.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+3

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  # Sử dụng bộ icon của iOS
  cupertino_icons: ^1.0.5

  # Common
  intl: 0.17.0

  # GetX
  get: ^4.6.5

  # Flutter
  flutter:
    sdk: flutter

  # Pin code Field
  pin_code_fields: ^7.4.0

  # Toast
  fluttertoast: ^8.2.2

  # 設定保存 - https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.1.2

  # To go to UID or page Link
  url_launcher: ^6.1.11

  # Cái loading splash dùng json làm ảnh nên convert bằng lottie
  lottie: ^2.3.2

  # Date Time Picker
  flutter_datetime_picker: ^1.5.1

  # Chọn Avatar
  image_picker: ^0.8.9
  photo_manager: ^2.6.0
  path_provider: ^2.0.15
  permission_handler: ^10.3.0

  # Chọn đầu số đt
  country_list_pick: ^1.0.1+6

  # Slideshow
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  loader_overlay: ^2.2.0
  build_runner: ^2.3.3
  fl_paging: ^2.2.0
  firebase_storage: ^11.2.3
  firebase_analytics: ^10.4.3

  flutter_flavorizr: ^2.1.6

  # Multi language
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.1
  flutter_test:
    sdk: flutter
  # Change icon
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "images/logo.png"


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
  #    - assets/dummy/
  #    - assets/dummy/update-user/
  #    - assets/dummy/update-kibou/
  #    - assets/dummy/update-job-career/
  #    - assets/dummy/group/
  #    - assets/dummy/group/1/
  #    - assets/dummy/question/
  #    - assets/dummy/question/1/
  #    - assets/dummy/video/1/
  #    - assets/dummy/answer/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-ExtraBold.ttf
          style: normal
          weight: 800
        - asset: fonts/Nunito/Nunito-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/Nunito/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Nunito/Nunito-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Nunito/Nunito-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
          style: normal
          weight: 500

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/Roboto/Roboto-Regular.ttf
          style: normal
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Configuration for Flavors
flavorizr:
  instructions:
    - assets:download
    - assets:extract

    #    Android
    - android:androidManifest
    - android:buildGradle
    - android:dummyAssets
    - android:icons

    #     iOS
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:dummyAssets
    - ios:icons
    - ios:plist

    #     Google
    - google:firebase

    #     Cleanup
    - assets:clean

    #     IDE
    - ide:config
  flavors:
    prod:
      app:
        name: "PetNotto"
        icon: "assets/logo_prod.jpeg"
      android:
        applicationId: "com.ducht.petdok.kuxxxx"
        firebase:
          config: "config/prod/google-services.json"
      ios:
        bundleId: "com.ducht.petdok.kuxxxx"
        firebase:
          config: "config/prod/GoogleService-Info.plist"